spring.application.name=todo-app

# データベース接続設定
spring.datasource.url=jdbc:postgresql://localhost:5432/todo_app
spring.datasource.username=postgres
spring.datasource.password=Hosa318847
spring.datasource.driver-class-name=org.postgresql.Driver

# MyBatis 設定（SQLとJavaを結びつける）
# アンダースコア（start_date）をキャメルケース（startDate）に自動変換する
mybatis.configuration.map-underscore-to-camel-case=true

# MyBatisが実行したSQLと結果をコンソールに表示する
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

# MyBatisの内部的な動きを詳しく見る（デバッグ用）
logging.level.sample.common.dao.mapper=DEBUG