spring.application.name=todo-app

# データベース接続設定
spring.datasource.url=jdbc:postgresql://localhost:5432/todo_app
spring.datasource.username=postgres
spring.datasource.password=Hosa318847
spring.datasource.driver-class-name=org.postgresql.Driver

# パスワードハッシュ化方式
password.hash.code=SHA-256

# Thymeleaf設定
spring.thymeleaf.mode=HTML

# MyBatis 設定
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
mybatis.type-aliases-package=sample.common.dao.entity
mybatis.mapper-locations=classpath:sample/common/dao/mapper/*.xml

# ログレベル設定
logging.level.sample.*=DEBUG

# セッション有効期限設定
server.servlet.session.timeout=1d